/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OrganizationRouteImport } from './routes/organization'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as HelpRouteImport } from './routes/help'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AllocationsRouteImport } from './routes/allocations'
import { Route as AiRouteImport } from './routes/ai'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssetsIndexRouteImport } from './routes/assets.index'
import { Route as AssetsRegisterRouteImport } from './routes/assets.register'
import { Route as AssetsPassportIdRouteImport } from './routes/assets.passport.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationRoute = OrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AllocationsRoute = AllocationsRouteImport.update({
  id: '/allocations',
  path: '/allocations',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsIndexRoute = AssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRegisterRoute = AssetsRegisterRouteImport.update({
  id: '/assets/register',
  path: '/assets/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsPassportIdRoute = AssetsPassportIdRouteImport.update({
  id: '/assets/passport/$id',
  path: '/assets/passport/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/ai': typeof AiRoute
  '/allocations': typeof AllocationsRoute
  '/audit': typeof AuditRoute
  '/bookings': typeof BookingsRoute
  '/contact': typeof ContactRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/features': typeof FeaturesRoute
  '/help': typeof HelpRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/notifications': typeof NotificationsRoute
  '/organization': typeof OrganizationRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/assets/register': typeof AssetsRegisterRoute
  '/assets/': typeof AssetsIndexRoute
  '/assets/passport/$id': typeof AssetsPassportIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/ai': typeof AiRoute
  '/allocations': typeof AllocationsRoute
  '/audit': typeof AuditRoute
  '/bookings': typeof BookingsRoute
  '/contact': typeof ContactRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/features': typeof FeaturesRoute
  '/help': typeof HelpRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/notifications': typeof NotificationsRoute
  '/organization': typeof OrganizationRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/assets/register': typeof AssetsRegisterRoute
  '/assets': typeof AssetsIndexRoute
  '/assets/passport/$id': typeof AssetsPassportIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/ai': typeof AiRoute
  '/allocations': typeof AllocationsRoute
  '/audit': typeof AuditRoute
  '/bookings': typeof BookingsRoute
  '/contact': typeof ContactRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/features': typeof FeaturesRoute
  '/help': typeof HelpRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/notifications': typeof NotificationsRoute
  '/organization': typeof OrganizationRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/assets/register': typeof AssetsRegisterRoute
  '/assets/': typeof AssetsIndexRoute
  '/assets/passport/$id': typeof AssetsPassportIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/ai'
    | '/allocations'
    | '/audit'
    | '/bookings'
    | '/contact'
    | '/copilot'
    | '/dashboard'
    | '/demo'
    | '/features'
    | '/help'
    | '/insights'
    | '/login'
    | '/maintenance'
    | '/notifications'
    | '/organization'
    | '/profile'
    | '/reports'
    | '/search'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
    | '/assets/register'
    | '/assets/'
    | '/assets/passport/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/ai'
    | '/allocations'
    | '/audit'
    | '/bookings'
    | '/contact'
    | '/copilot'
    | '/dashboard'
    | '/demo'
    | '/features'
    | '/help'
    | '/insights'
    | '/login'
    | '/maintenance'
    | '/notifications'
    | '/organization'
    | '/profile'
    | '/reports'
    | '/search'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
    | '/assets/register'
    | '/assets'
    | '/assets/passport/$id'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/ai'
    | '/allocations'
    | '/audit'
    | '/bookings'
    | '/contact'
    | '/copilot'
    | '/dashboard'
    | '/demo'
    | '/features'
    | '/help'
    | '/insights'
    | '/login'
    | '/maintenance'
    | '/notifications'
    | '/organization'
    | '/profile'
    | '/reports'
    | '/search'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
    | '/assets/register'
    | '/assets/'
    | '/assets/passport/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AiRoute: typeof AiRoute
  AllocationsRoute: typeof AllocationsRoute
  AuditRoute: typeof AuditRoute
  BookingsRoute: typeof BookingsRoute
  ContactRoute: typeof ContactRoute
  CopilotRoute: typeof CopilotRoute
  DashboardRoute: typeof DashboardRoute
  DemoRoute: typeof DemoRoute
  FeaturesRoute: typeof FeaturesRoute
  HelpRoute: typeof HelpRoute
  InsightsRoute: typeof InsightsRoute
  LoginRoute: typeof LoginRoute
  MaintenanceRoute: typeof MaintenanceRoute
  NotificationsRoute: typeof NotificationsRoute
  OrganizationRoute: typeof OrganizationRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AssetsRegisterRoute: typeof AssetsRegisterRoute
  AssetsIndexRoute: typeof AssetsIndexRoute
  AssetsPassportIdRoute: typeof AssetsPassportIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization': {
      id: '/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allocations': {
      id: '/allocations'
      path: '/allocations'
      fullPath: '/allocations'
      preLoaderRoute: typeof AllocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/': {
      id: '/assets/'
      path: '/assets'
      fullPath: '/assets/'
      preLoaderRoute: typeof AssetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/register': {
      id: '/assets/register'
      path: '/assets/register'
      fullPath: '/assets/register'
      preLoaderRoute: typeof AssetsRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/passport/$id': {
      id: '/assets/passport/$id'
      path: '/assets/passport/$id'
      fullPath: '/assets/passport/$id'
      preLoaderRoute: typeof AssetsPassportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AiRoute: AiRoute,
  AllocationsRoute: AllocationsRoute,
  AuditRoute: AuditRoute,
  BookingsRoute: BookingsRoute,
  ContactRoute: ContactRoute,
  CopilotRoute: CopilotRoute,
  DashboardRoute: DashboardRoute,
  DemoRoute: DemoRoute,
  FeaturesRoute: FeaturesRoute,
  HelpRoute: HelpRoute,
  InsightsRoute: InsightsRoute,
  LoginRoute: LoginRoute,
  MaintenanceRoute: MaintenanceRoute,
  NotificationsRoute: NotificationsRoute,
  OrganizationRoute: OrganizationRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AssetsRegisterRoute: AssetsRegisterRoute,
  AssetsIndexRoute: AssetsIndexRoute,
  AssetsPassportIdRoute: AssetsPassportIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
